OleTube/OleTube/urls.py
from django.contrib import admin
from django.urls import path, include
from api.views import index, video_detail
from users.views import profile


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('auth/', include('users.urls')),
    path('accounts/profile/', profile, name='profile'),
    path('videos/<int:video_id>/', video_detail, name='video_detail'),
    path('', index, name='index'),
]

OleTube/api/urls.py
from django.urls import path
from .views import (CreateVideoView, ListVideoView, DetailVideoView,
                    DeleteVideoView, like_video, dislike_video, add_comment,
                    get_comments, get_dislikes, get_likes)

app_name = 'api'

urlpatterns = [
    path('videos/', ListVideoView.as_view(), name='video-list'),
    path('videos/create/', CreateVideoView.as_view(), name='video-create'),
    path('videos/<int:id>/delete/', DeleteVideoView.as_view(), name='video-delete'),
    path('videos/like/<int:video_id>/', like_video, name='like-video'),
    path('videos/<int:id>/dislike/', dislike_video, name='dislike-video'),
    path('videos/<int:id>/comment/', add_comment, name='add-comment'),
    path('videos/<int:video_id>/likes/', get_likes, name='get_likes'),
    path('videos/<int:video_id>/dislikes/', get_dislikes, name='get_dislikes'),
    path('videos/<int:video_id>/comments/', get_comments, name='get_comments'),
]

OleTube/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView, PasswordResetView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='login.html'),
        name='login'
    ),
    path(
        'password_reset',
        PasswordResetView.as_view(),
        name='password_reset_form'
    ),
]

OleTube/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">OleTube</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'index' %}">Главная</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'api:video-create' %}" class="btn btn-primary">Создать новое видео</a>
        </li>

        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name == 'users:logout' %}active{% endif %}" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'profile' %}">Личный кабинет</a>
        </li>
        {% else %}
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name == 'users:login' %}active{% endif %}" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item"> 
          <a class="nav-link link-light {% if view_name == 'users:signup' %}active{% endif %}" href="{% url 'users:signup' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>
  <footer class="bg-light py-3" style="left: 0; bottom: 0; width: 100%; background-color: #f5f5f5; text-align: center; padding: 10px 0;">
    <div class="container">
      <p>&copy; OleTube</p>
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0pN" crossorigin="anonymous"></script>
</body>
</html>

OleTube/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
      {% for video in videos %}
        <div class="col-md-6">
          <div class="container">
            <h1 class="mb-4">
              <a class="nav-link" href="{% url 'video_detail' video.videooo.id%}">{{ video.videooo.title }}</a>
            </h1>
            <div class="embed-responsive embed-responsive-16by9 mb-3">
              <video class="embed-responsive-item" controls>
                <source src="{{ video.link }}" type="video/mp4">
                Ваш браузер не поддерживает тег video.
              </video>
            </div>
          </div>
        </div>
      {% endfor %} 
    </div>
  </div>
{% endblock %}

OleTube/templates/logged_out.html
{# Это код файла templates/users/logged_out.html #}

{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

OleTube/templates/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

OleTube/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>Личный кабинет</h1>
<p>Имя пользователя: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>

<h1>Ваши видео:</h1>
<hr style="height:5px; width:100%; border-width:0; color:red; background-color:red">
<div class="row">  
    {% for video in user_video %}
        <div class="col-md-6">
            <h2>               
                <a class="nav-link" href="{% url 'video_detail' video.video.id %}">{{ video.video.title }}</a>
            </h2>
            <video src="{{ video.video.url }}" controls width="400" height="225"></video>
        </div>
        {% if forloop.counter|divisibleby:2 %}
            </div>
            <div class="row">
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

OleTube/templates/signup.html
<!-- templates/users/signup.html -->

{% extends "base.html" %}
{% block title %}<title>Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
          <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
              {% if form.errors %}
                  {% for field in form %} 
                    {% for error in field.errors %}            
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
              {% endif %}

              <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}

              {# Выводим поля в цикле, по отдельности #}
              {% for field in form %} 
                <div class="form-group row my-3">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                      {% if field.field.required %}
                        <span class="required text-danger">*</span>
                      {% endif %}
                  </label>
                  {# К полю ввода добавляем атрибут class #}
                  {{ field|addclass:'form-control' }} 
                    {% if field.help_text %}
                      <small 
                         id="{{ field.id_for_label }}-help"
                         class="form-text text-muted"
                      >
                        {{ field.help_text|safe }}
                      </small>
                    {% endif %}
                </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Зарегистрироваться
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

OleTube/templates/video_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
      <div class="col-md-8">
        <div class="card">
          <div class="card-body">
            <h1 class="card-text">{{ video.title }}</h1>
          </div>
        </div>
        <div class="embed-responsive embed-responsive-16by9 mb-3">
            <video class="embed-responsive-item" controls>
              <source src="{{ video.url }}" type="video/mp4">
              Ваш браузер не поддерживает тег video.
            </video>
          </div>
          <div class="card">
            <div class="card-body">
              <p class="card-text">{{ video.description }}</p>
            </div>
          </div>
          <p class="mt-4">Лайки: <span id="likes-{{ video.likes_count }}">{{ video.likes_count }}</span></p>
          <p>Дизлайки: <span id="dislikes-{{ video.videooo.dislike_count }}">{{ video.dislike_count  }}</span></p>

          <div class="mt-4">
            <form action="/api/videos/like/{{ video.id }}/" method="POST">
              {% csrf_token %}
              <button class="btn btn-danger" type="submit">Like</button>
            </form>
            <form action="/api/videos/{{ video.id }}/dislike/" method="POST">
              {% csrf_token %}
              <button class="btn btn-danger" type="submit">Dislike</button>
            </form>
          </div>

          <form class="mt-4" id="comment-form-{{ video.id }}" method="POST" action="/api/videos/{{ video.id }}/comment/">
            {% csrf_token %}
            <input type="hidden" name="video_id" value="{{ video.id }}">
            <div class="form-group">
              <label for="comment-{{ video.id }}">Оставьте комментарий:</label>
              <textarea class="form-control" name="content" id="comment-{{ video.id }}" rows="3"></textarea>
            </div>
            <button class="btn btn-danger" type="submit">Отправить</button>
          </form>

          <h2 class="mt-4">Comments</h2>
          <div id="comments-{{ video.id }}">
            {% for comment in video.comments.all %}
              <div class="card mb-3">
                <div class="card-header">{{ comment.user.username }}</div>
                <div class="card-body">
                  <p class="card-text">{{ comment.content }}</p>
                </div>
              </div>
            {% empty %}
              <p>Пока нет комментариев.</p>
            {% endfor %}
          </div>
      </div>
      <div class="col-md-4">
        <h2>Другие видео автора:</h2>
        {% for v in user_videos %}
          <div class="card mb-3">
            <div class="card-body">
              <h5 class="mb-4">
                <a class="nav-link" href="{% url 'video_detail' v.id %}">{{ v.title }}</a>
              </h5>
            </div>
          </div>
        {% empty %}
          <p>У этого автора пока нет других видео.</p>
        {% endfor %}
      </div>
    </div>
  </div>
<hr style="height:5px; width:100%; border-width:0; color:red; background-color:red">
{% endblock %}

OleTube/templates/video_upload.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h1>Загрузка видео</h1>
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <label for="title">Название</label>
      <input type="text" class="form-control" id="title" name="title" required>
    </div>
    <div class="form-group">
      <label for="description">Описание</label>
      <textarea class="form-control" id="description" name="description"></textarea>
    </div>
    <div class="form-group">
      <label for="video_file">Видеофайл (MP4)</label>
      <input type="file" class="form-control-file" id="video_file" name="video_file" required>
    </div>
    <button type="submit" class="btn btn-primary">Загрузить</button>
  </form>
</div>
{% endblock %}